import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
// The source of truth comes through the server db barrel (apps/web may not import
// @quackback/db directly). It drags postgres, which is fine in this node test.
import {
  PERMISSIONS as DB_PERMISSIONS,
  ALL_PERMISSIONS as DB_ALL_PERMISSIONS,
  PERMISSION_CATEGORIES as DB_PERMISSION_CATEGORIES,
  SYSTEM_ROLES as DB_SYSTEM_ROLES,
  SYSTEM_ROLE_PERMISSIONS as DB_SYSTEM_ROLE_PERMISSIONS,
  WORKSPACE_ADMIN_PERMISSIONS as DB_WORKSPACE_ADMIN_PERMISSIONS,
  PERMISSION_CATALOGUE as DB_PERMISSION_CATALOGUE,
  presetForLegacyRole as dbPresetForLegacyRole,
  renderPermissionsMirror,
} from '@/lib/server/db'
import * as mirror from '../permissions'

// The client mirror (apps/web/.../permissions.ts) duplicates the @quackback/db
// catalogue because client bundles can't import the db package. This guards the
// two from drifting: edit the db catalogue first, then mirror the change here.
describe('permission catalogue mirror', () => {
  it('PERMISSIONS is identical to the source of truth', () => {
    expect(mirror.PERMISSIONS).toEqual(DB_PERMISSIONS)
  })

  it('ALL_PERMISSIONS matches', () => {
    expect(new Set(mirror.ALL_PERMISSIONS)).toEqual(new Set(DB_ALL_PERMISSIONS))
    expect(mirror.ALL_PERMISSIONS.length).toBe(DB_ALL_PERMISSIONS.length)
  })

  it('PERMISSION_CATEGORIES matches', () => {
    expect(new Set(mirror.PERMISSION_CATEGORIES)).toEqual(new Set(DB_PERMISSION_CATEGORIES))
  })

  it('the role presets match', () => {
    expect(mirror.SYSTEM_ROLES).toEqual(DB_SYSTEM_ROLES)
    expect(new Set(mirror.WORKSPACE_ADMIN_PERMISSIONS)).toEqual(
      new Set(DB_WORKSPACE_ADMIN_PERMISSIONS)
    )
    for (const role of Object.values(DB_SYSTEM_ROLES)) {
      expect(new Set(mirror.SYSTEM_ROLE_PERMISSIONS[role])).toEqual(
        new Set(DB_SYSTEM_ROLE_PERMISSIONS[role])
      )
    }
    for (const legacy of ['admin', 'member', 'user']) {
      expect(mirror.presetForLegacyRole(legacy)).toBe(dbPresetForLegacyRole(legacy))
    }
  })

  it('the catalogue (key, category) projection matches', () => {
    const proj = (c: ReadonlyArray<{ key: string; category: string }>): string[] =>
      c.map((p) => `${p.key}:${p.category}`).sort()
    expect(proj(mirror.PERMISSION_CATALOGUE)).toEqual(proj(DB_PERMISSION_CATALOGUE))
  })

  it('the committed mirror is byte-identical to the generator output', () => {
    // permissions.ts is generated by `bun run db:permissions` — hand edits
    // here fail, and the fix is to edit the catalogue and regenerate.
    const file = readFileSync(join(import.meta.dirname, '../permissions.ts'), 'utf8')
    expect(file).toBe(renderPermissionsMirror())
  })
})
